const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {getPersonalDataPath}=require('./personal-data.cjs');
const data=JSON.parse(fs.readFileSync(getPersonalDataPath('application-data.json'),'utf8')),emails=JSON.parse(fs.readFileSync(getPersonalDataPath('application-emails.json'),'utf8'));
const {completeCost}=require('./completion-cost.cjs');
const applicationPolicies=require('./application-policies.cjs');
function catalog(){return [...data.professors.map(p=>({id:'phd-'+p.id,kind:'PhD',school:p.schoolShort,title:p.admissions?.program||p.department||p.schoolShort,professor:p.name,deadline:p.admissions?.deadline||p.waiver?.finalApplicationDeadline||'',deadlineContext:p.admissions?.deadlineContext||'',feeUsd:p.admissions?.finance?.applicationFeeUsd??null,feeOriginal:p.admissions?.finance?.applicationFeeOriginal||'',feeNote:p.admissions?.finance?.applicationFeeNote||'',url:p.admissions?.applyUrl||p.admissions?.programUrl||p.website||'',category:p.category,feeWaiver:p.feeWaiver,waiver:p.admissions?.waiver||p.waiver||null})),...data.masters.map(p=>({id:p.id,kind:'MS',school:p.university,title:p.program,deadline:p.deadline||'',deadlineContext:p.deadlineContext||'',feeUsd:p.finance?.applicationFeeUsd??null,feeOriginal:p.finance?.applicationFeeOriginal||'',feeNote:p.finance?.applicationFeeNote||'',url:p.applyUrl||p.programUrl||'',feeWaiver:p.feeWaiver,completionCost:p.completionCost,waiver:p.waiver||null}))];}
function dayKey(now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Vancouver',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);}
function days(date,now=new Date()){return Math.round((Date.parse(date+'T00:00:00Z')-Date.parse(dayKey(now)+'T00:00:00Z'))/86400000);}
function createApplications({app,google,onChange=()=>{},now=()=>new Date(),initialSelect=true,fetchRate=globalThis.fetch}){
 const filename=path.join(app.getPath('userData'),'applications.json'),items=catalog(),byId=new Map(items.map(i=>[i.id,i]));
 let exchangeError='',exchangeRunning=false;
 let store={version:1,selected:Object.fromEntries(items.map(i=>[i.id,initialSelect&&!!i.deadline&&i.category!=='基本拒绝'])),fees:{},budget:{usdCny:data.finance.usdCny,extraUsd:0},events:{},epochs:{},syncedAt:null},loadError='',syncError='',running=null,dirty=false;
 try{if(fs.existsSync(filename)){const saved=JSON.parse(fs.readFileSync(filename,'utf8'));if(saved.version!==1||!saved.selected||!saved.events)throw Error();store={...store,...saved};}}catch{loadError='申请配置读取失败，原文件已保留，暂停更改和日历同步。';}

 if(store.budget.autoExchange===undefined){store.budget={...store.budget,autoExchange:true,usdCny:data.finance.usdCny};}
 if(!store.exchange)store.exchange={usdCny:data.finance.usdCny,cadUsd:data.finance.cadUsd,asOf:data.finance.asOf,source:data.finance.source};
 async function refreshExchange(){if(!fetchRate||exchangeRunning||loadError)return;exchangeRunning=true;try{const r=await fetchRate(data.finance.source,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('汇率服务暂不可用');const x=await r.json();if(x.base!=='USD'||!/^\d{4}-\d{2}-\d{2}$/.test(x.date)||!(x.rates?.CNY>0&&x.rates?.CNY<100&&x.rates?.CAD>0&&x.rates?.CAD<100))throw Error('汇率响应无效');store.exchange={usdCny:x.rates.CNY,cadUsd:1/x.rates.CAD,asOf:x.date,source:data.finance.source,fetchedAt:new Date().toISOString()};if(store.budget.autoExchange!==false)store.budget.usdCny=x.rates.CNY;exchangeError='';save();changed();}catch(e){exchangeError='最新汇率获取失败，沿用 '+store.exchange.asOf+' 的参考价';changed();}finally{exchangeRunning=false;}}
 function save(){if(loadError)throw Error(loadError);fs.mkdirSync(path.dirname(filename),{recursive:true});fs.writeFileSync(filename+'.tmp',JSON.stringify(store,null,2));fs.renameSync(filename+'.tmp',filename);}
 function changed(){onChange();}
 function defaultFee(i){const match=/CAD\s*([\d,.]+)/i.exec(i.feeOriginal);return match?Math.round(Number(match[1].replaceAll(',',''))*(store.exchange?.cadUsd||data.finance.cadUsd)*100)/100:i.feeUsd;}
 function totals(){let gross=0,net=0,unknown=0,waived=0;for(const i of items.filter(i=>store.selected[i.id])){const f=store.fees[i.id]||{},fee=f.overrideUsd??defaultFee(i);if(fee===null){unknown++;continue;}gross+=fee;if(f.waived)waived+=fee;else net+=fee;}return {grossUsd:gross,waivedUsd:waived,applicationUsd:net,extraUsd:store.budget.extraUsd,totalUsd:net+store.budget.extraUsd,totalCny:(net+store.budget.extraUsd)*store.budget.usdCny,unknown};}
 function get(){const today=dayKey(now()),selected=items.filter(i=>store.selected[i.id]),future=selected.filter(i=>/^\d{4}-\d{2}-\d{2}$/.test(i.deadline)&&i.deadline>=today).sort((a,b)=>a.deadline.localeCompare(b.deadline));const next=future[0];return {ok:!loadError,conflicts:applicationPolicies.conflicts(items.map(i=>({...i,selected:!!store.selected[i.id]}))),items:items.map(i=>({...i,applicationPolicy:applicationPolicies.policy(i),feeUsd:defaultFee(i),completionCost:completeCost(i.completionCost,{usdCny:store.budget.usdCny,cadUsd:store.exchange?.cadUsd||data.finance.cadUsd},store.fees[i.id]?.waived?0:store.fees[i.id]?.overrideUsd??defaultFee(i)),selected:!!store.selected[i.id],fee:store.fees[i.id]||{},calendar:store.events[i.id]||null})),budget:store.budget,totals:totals(),snapshot:data.snapshot,finance:{...data.finance,...store.exchange,manual:store.budget.autoExchange===false,exchangeError},selectedCount:selected.length,ubc:{date:data.visitEndDate||'',days:data.visitEndDate?days(data.visitEndDate,now()):null},next:next?{...next,days:days(next.deadline,now()),sameDayCount:future.filter(i=>i.deadline===next.deadline).length}:null,sync:{running:!!running,calendarWrite:google.connection().calendarWrite,lastSynced:store.syncedAt,pending:items.filter(i=>needsSync(i)).length,error:loadError||syncError,needsAuthorization:!google.connection().calendarWrite}};}
 function money(value){if(typeof value!=='number'||!Number.isFinite(value)||value<0||value>1e7)throw Error('费用需要是有效的非负数字。');return value;}
 function update(input){const item=byId.get(input?.id);if(!item)throw Error('申请项目不存在。');if(input.selected!==undefined&&typeof input.selected!=='boolean')throw Error('申请选择无效。');const fee={...store.fees[item.id]};if(input.overrideUsd!==undefined)fee.overrideUsd=input.overrideUsd===null?null:money(input.overrideUsd);if(input.waived!==undefined){if(typeof input.waived!=='boolean')throw Error('减免状态无效。');fee.waived=input.waived;}if(input.selected!==undefined&&input.selected!==store.selected[item.id]){store.selected[item.id]=input.selected;if(input.selected)store.epochs[item.id]=crypto.randomUUID();}store.fees[item.id]=fee;save();changed();queue();return get();}
 function budget(input){const next={...store.budget};if(input?.usdCny!==undefined){next.usdCny=money(input.usdCny);if(!next.usdCny||next.usdCny>10000)throw Error('汇率不正确。');}if(input?.extraUsd!==undefined)next.extraUsd=money(input.extraUsd);if(input?.usdCny!==undefined&&input.usdCny!==store.budget.usdCny)next.autoExchange=false;if(input?.autoExchange===true){next.autoExchange=true;next.usdCny=store.exchange?.usdCny||data.finance.usdCny;}store.budget=next;save();changed();if(input?.autoExchange===true)refreshExchange();return get();}
 function eventBody(i){const end=new Date(Date.parse(i.deadline+'T00:00:00Z')+86400000).toISOString().slice(0,10);return {summary:`[${i.kind}申请截止] ${i.title}`,description:`[Orbit Application: ${i.id}]\n学校：${i.school}\n${i.professor?'教授：'+i.professor+'\n':''}截止日期：${i.deadline}\n${i.deadlineContext}\n来源：PhD申请助手，数据快照 ${data.snapshot}\n${i.url}\n具体提交时刻和学校时区请以项目官网为准。`,start:{date:i.deadline},end:{date:end},transparency:'transparent',reminders:{useDefault:false,overrides:[]},extendedProperties:{private:{orbitWorkspace:'applications',orbitApplicationId:i.id}}};}
 function fingerprint(i){return crypto.createHash('sha256').update(JSON.stringify(eventBody(i))).digest('hex');}
 function needsSync(i){const e=store.events[i.id];return !!(store.selected[i.id]&&i.deadline?( !e||e.status!=='synced'||e.fingerprint!==fingerprint(i)) :e);}
 function epochId(i){return 'orbit'+crypto.createHash('sha256').update(i.id+'|'+(store.epochs[i.id]||'initial')).digest('hex').slice(0,45);}
 function queue(){dirty=true;if(!running)setImmediate(()=>sync().catch(()=>{}));}
 async function sync(){if(running){dirty=true;await running;return get();}if(loadError)return get();if(!google.connection().calendarWrite){changed();return get();}
  running=(async()=>{syncError='';do{dirty=false;for(const i of items){if(!needsSync(i))continue;const desired=!!store.selected[i.id]&&!!i.deadline;let entry=store.events[i.id];try{
    if(desired){if(!entry){entry={id:epochId(i),status:'pending'};store.events[i.id]=entry;save();}const body=eventBody(i);await google.syncApplicationEvent({id:entry.id,applicationId:i.id,body});entry.status='synced';entry.fingerprint=fingerprint(i);entry.syncedAt=now().toISOString();save();}
    else if(entry){await google.syncApplicationEvent({id:entry.id,applicationId:i.id,remove:true});delete store.events[i.id];save();}
    changed();if(!!store.selected[i.id]!==desired)dirty=true;
   }catch(error){syncError=`${i.school}：${error.message}`;if(entry){entry.status='error';entry.error=error.message;save();}changed();break;}}
   if(!syncError&&!items.some(needsSync)){store.syncedAt=now().toISOString();save();}
  }while(dirty&&!syncError);})().finally(()=>{running=null;changed();});changed();await running;return get();
 }
 function readEmail(name){if(typeof name!=='string'||!Object.hasOwn(emails,name))throw Error('邮件记录不存在。');return emails[name];}
 if(!loadError&&!fs.existsSync(filename))save();
 const timer=setInterval(()=>{if(items.some(needsSync)&&google.connection().calendarWrite)queue();changed();},60000);timer.unref?.();queue();
 const exchangeTimer=setInterval(refreshExchange,6*60*60*1000);exchangeTimer.unref?.();setImmediate(refreshExchange);
 return {get,update,budget,sync,email:readEmail,dispose:()=>{clearInterval(timer);clearInterval(exchangeTimer);}};
}
module.exports={createApplications,catalog,days,dayKey};
