const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const time=require('../dist/timezone.js');const {parseMeetingLink}=require('./links.cjs');
function cleanEvent(input,zone='Asia/Shanghai',previous={}){
 if(!input||typeof input!=='object'||Array.isArray(input))throw Error('日程参数应为 JSON 对象。');const e={...previous,...input};const title=String(e.title||'').trim();if(!title||title.length>200)throw Error('日程名称需为 1–200 个字符。');
 const selected=time.normalize(input.timeZone||zone),date=input.date??(previous.startAt?time.dateKey(previous.startAt,selected):e.date),clock=input.time??(previous.startAt?time.clock(previous.startAt,selected):e.time);let startAt;if(input.startAt){if(typeof input.startAt!=='string'||!/(?:Z|[+-]\d{2}:\d{2})$/.test(input.startAt))throw Error('startAt 需为带时区的 ISO 时间。');startAt=new Date(input.startAt).toISOString();}else if(input.date!==undefined||input.time!==undefined||!previous.startAt)startAt=time.localInstant(date,clock,selected);else startAt=previous.startAt;
 const duration=Number(e.duration??30);if(!Number.isFinite(duration)||duration<5||duration>1440)throw Error('时长需为 5–1440 分钟。');const zoomLink=String(e.zoomLink||'').trim();if(zoomLink&&!parseMeetingLink(zoomLink))throw Error('Zoom 链接无效。');
 return {id:previous.id||String(e.id||'local:'+crypto.randomUUID()).slice(0,256),title,startAt,date:time.dateKey(startAt,selected),time:time.clock(startAt,selected),timeZone:selected,duration,location:String(e.location||'').slice(0,300),notes:String(e.notes||'').slice(0,16000),zoomLink,type:['blue','green','orange'].includes(e.type)?e.type:'blue'};
}
function createEvents({app,safeStorage,getTimeZone,onChange=()=>{}}){const filename=path.join(app.getPath('userData'),'local-events.enc');let events=[],initialized=false,failed=false;
 try{if(fs.existsSync(filename)){events=JSON.parse(safeStorage.decryptString(fs.readFileSync(filename)));if(!Array.isArray(events))throw Error();initialized=true;}}catch{failed=true;}
 function commit(next){if(failed)throw Error('本地日程无法解密，已保留原文件。');if(!safeStorage.isEncryptionAvailable())throw Error('Windows 日程加密不可用。');fs.mkdirSync(path.dirname(filename),{recursive:true});fs.writeFileSync(filename+'.tmp',safeStorage.encryptString(JSON.stringify(next)));fs.renameSync(filename+'.tmp',filename);events=next;initialized=true;onChange(get().events);return {ok:true};}
 function get(){return {initialized,events:events.map(e=>({...e,date:time.dateKey(e.startAt,getTimeZone()),time:time.clock(e.startAt,getTimeZone()),timeZone:getTimeZone()}))};}
 return {get,replace:input=>{if(!Array.isArray(input)||input.length>5000)throw Error('本地日程数据不正确。');return commit(input.map(e=>cleanEvent(e,getTimeZone())));},create:input=>{const e=cleanEvent(input,getTimeZone());if(events.some(x=>x.id===e.id))throw Error('日程 ID 已存在。');commit([...events,e]);return e;},update:(id,input)=>{const index=events.findIndex(e=>e.id===id);if(index<0)throw Error('未找到日程。');const e=cleanEvent(input,getTimeZone(),events[index]);const next=[...events];next[index]=e;commit(next);return e;},remove:id=>{if(!events.some(e=>e.id===id))throw Error('未找到日程。');return commit(events.filter(e=>e.id!==id));}};
}
module.exports={createEvents,cleanEvent};
