const time=require('../dist/timezone.js');
const {parseMeetingLink}=require('./links.cjs');
function meetingLink(event){
 const text=[event.location,event.description,event.conferenceData?.entryPoints?.map(p=>p.uri).join(' ')].filter(Boolean).join(' ').replaceAll('&amp;','&');
 for(const candidate of text.match(/https:\/\/[a-zA-Z0-9.-]+\/(?:j|my|wc\/join)\/[^\s<>"']+/g)||[]){const link=parseMeetingLink(candidate.replace(/[.,;，。；)]+$/,''));if(link)return link;}return '';
}
function attending(event){return event.status!=='cancelled'&&event.attendees?.find(a=>a.self)?.responseStatus!=='declined';}
function displayEvent(event,calendar,zone){const start=event.start?.dateTime,end=event.end?.dateTime;
 return {id:'google:'+calendar.id+':'+event.id,title:event.summary||'（无标题）',date:start?time.dateKey(start,zone):event.start?.date,time:start?time.clock(start,zone):'全天',startAt:start||null,allDay:!start,duration:start&&end?Math.max(0,Math.round((Date.parse(end)-Date.parse(start))/60000)):1440,location:event.location||'',notes:(event.description||'').replace(/<[^>]*>/g,''),zoomLink:meetingLink(event),htmlLink:event.htmlLink||'',remote:true,type:'blue',calendarName:calendar.summary||'Google Calendar',responseStatus:event.organizer?.self?'organizer':event.attendees?.find(a=>a.self)?.responseStatus||'',recurring:!!event.recurringEventId,identity:(event.iCalUID||calendar.id+':'+event.id)+'@'+(start||event.start?.date)};
}
async function mapConcurrent(items,fn){const results=new Array(items.length);let next=0;await Promise.all(Array.from({length:Math.min(4,items.length)},async()=>{while(next<items.length){const index=next++;try{results[index]={ok:true,value:await fn(items[index])};}catch(error){results[index]={ok:false,error:error.message,calendar:items[index].summary||items[index].id};}}}));return results;}
function createMeetingReader({api,getTimeZone,now=()=>new Date()}){
 let calendarCache=null,cacheAt=0,listPending=null;
 async function calendars(){if(calendarCache&&Date.now()-cacheAt<300000)return calendarCache;if(listPending)return listPending;listPending=(async()=>{let nextPage,items=[];do{const u=new URL('https://www.googleapis.com/calendar/v3/users/me/calendarList');u.searchParams.set('maxResults','250');u.searchParams.set('minAccessRole','reader');if(nextPage)u.searchParams.set('pageToken',nextPage);const data=await api(u.href);items.push(...(data.items||[]).filter(c=>!c.deleted));nextPage=data.nextPageToken;}while(nextPage);items.sort((a,b)=>Number(!!b.primary)-Number(!!a.primary));calendarCache=items.length?items:[{id:'primary',summary:'Google Calendar'}];cacheAt=Date.now();return calendarCache;})();try{return await listPending;}finally{listPending=null;}}
 async function list(calendar,params){let nextPage,events=[];do{const u=new URL('https://www.googleapis.com/calendar/v3/calendars/'+encodeURIComponent(calendar.id)+'/events');Object.entries({...params,maxResults:'2500',showHiddenInvitations:'true',showDeleted:'false'}).forEach(([k,v])=>u.searchParams.set(k,v));if(nextPage)u.searchParams.set('pageToken',nextPage);const data=await api(u.href);events.push(...(data.items||[]).filter(attending));nextPage=data.nextPageToken;}while(nextPage);return events;}
 async function nextInstance(calendar,event,start){let pageToken;do{const u=new URL('https://www.googleapis.com/calendar/v3/calendars/'+encodeURIComponent(calendar.id)+'/events/'+encodeURIComponent(event.id)+'/instances');u.searchParams.set('timeMin',start);u.searchParams.set('maxResults','50');u.searchParams.set('showDeleted','false');if(pageToken)u.searchParams.set('pageToken',pageToken);const data=await api(u.href);const match=(data.items||[]).filter(attending).filter(e=>Date.parse(e.start?.dateTime||e.start?.date)>=Date.parse(start)).sort((a,b)=>Date.parse(a.start?.dateTime||a.start?.date)-Date.parse(b.start?.dateTime||b.start?.date))[0];if(match)return {...event,...match,recurrence:undefined,recurringEventId:event.id};pageToken=data.nextPageToken;}while(pageToken);return null;}
 function collect(results,zone){const unique=new Map();for(const result of results)if(result.ok)for(const event of result.value){const old=unique.get(event.identity);if(!old||event.recurring)unique.set(event.identity,event);}const errors=results.filter(r=>!r.ok).map(r=>r.calendar+'：'+r.error);return {status:results.every(r=>!r.ok)?'error':errors.length?'partial':'success',events:[...unique.values()].sort((a,b)=>(a.startAt||a.date).localeCompare(b.startAt||b.date)),errors,updatedAt:Date.now(),timeZone:zone};}
 async function getMeetings(){const zone=getTimeZone(),start=now().toISOString(),items=await calendars();
 const results=await mapConcurrent(items,async calendar=>{const events=await list(calendar,{timeMin:start,singleEvents:'false',orderBy:'updated'});const zoom=events.filter(e=>meetingLink(e));const expanded=await mapConcurrent(zoom,async e=>e.recurrence?await nextInstance(calendar,e,start):e);const failure=expanded.find(r=>!r.ok);if(failure)throw Error(failure.error);return expanded.filter(r=>r.value).map(r=>displayEvent(r.value,calendar,zone));});return collect(results,zone);
 }
 async function getReminderEvents(){const zone=getTimeZone(),start=now(),items=await calendars();const results=await mapConcurrent(items,async calendar=>(await list(calendar,{timeMin:new Date(start.getTime()-300000).toISOString(),timeMax:new Date(start.getTime()+86400000).toISOString(),singleEvents:'true',orderBy:'startTime'})).map(e=>displayEvent(e,calendar,zone)));const combined=collect(results,zone);if(combined.status!=='success')throw Error(combined.errors.join('；'));return combined.events;}
 return {getMeetings,getReminderEvents,clear:()=>{calendarCache=null;cacheAt=0;}};
}
module.exports={createMeetingReader,displayEvent,attending,meetingLink};
