const {contextBridge,ipcRenderer}=require('electron');
contextBridge.exposeInMainWorld('orbitDesktop',Object.freeze({
  platform:'windows',
  showDownloads:bounds=>ipcRenderer.invoke('orbit:downloads-show',bounds),
  closeDownloads:()=>ipcRenderer.invoke('orbit:downloads-close'),
  onDownloadsVisibility:callback=>{const handler=(_event,value)=>callback(value);ipcRenderer.on('orbit:downloads-visibility',handler);return ()=>ipcRenderer.removeListener('orbit:downloads-visibility',handler);},
  getDownloads:()=>ipcRenderer.invoke('orbit:downloads-get'),
  downloadAction:(id,action)=>ipcRenderer.invoke('orbit:downloads-action',id,action),
  onDownloadsChanged:callback=>{const handler=(_event,data)=>callback(data);ipcRenderer.on('orbit:downloads-changed',handler);return ()=>ipcRenderer.removeListener('orbit:downloads-changed',handler);},
  workspaceAction:(mode,action,value)=>ipcRenderer.invoke('orbit:workspace-action',mode,action,value),
  onWorkspaceState:callback=>{const handler=(_event,state)=>callback(state);ipcRenderer.on('orbit:workspace-state',handler);return ()=>ipcRenderer.removeListener('orbit:workspace-state',handler);},
  onWorkspaceFocus:callback=>{const handler=()=>callback();ipcRenderer.on('orbit:workspace-focus',handler);return ()=>ipcRenderer.removeListener('orbit:workspace-focus',handler);},
  openPdf:()=>ipcRenderer.invoke('orbit:pdf-open'),
  getNavigation:()=>ipcRenderer.invoke('orbit:navigation-get'),
  saveNavigation:input=>ipcRenderer.invoke('orbit:navigation-save',input),
  deleteNavigation:id=>ipcRenderer.invoke('orbit:navigation-delete',id),
  reorderNavigation:ids=>ipcRenderer.invoke('orbit:navigation-reorder',ids),
  pickNavigationIcon:()=>ipcRenderer.invoke('orbit:navigation-icon'),
  showNavigationMenu:id=>ipcRenderer.invoke('orbit:navigation-menu',id),
  onNavigationAction:callback=>{const handler=(_event,action)=>callback(action);ipcRenderer.on('orbit:navigation-action',handler);return ()=>ipcRenderer.removeListener('orbit:navigation-action',handler);},
  saveLanguage:language=>ipcRenderer.invoke('orbit:language-save',language),
  getTimeZone:()=>ipcRenderer.invoke('orbit:time-zone'),
  saveTimeZone:zone=>ipcRenderer.invoke('orbit:save-time-zone',zone),
  getLoginSettings:()=>ipcRenderer.invoke('orbit:login-settings'),
  saveLoginSettings:(input)=>ipcRenderer.invoke('orbit:login-config',input),
  forgetLogin:(id)=>ipcRenderer.invoke('orbit:login-forget',id),
  openExternal:(url)=>ipcRenderer.invoke('orbit:open-website',url),
  openWebsite:(url)=>ipcRenderer.invoke('orbit:open-website',url),
  navigateWebsite:(id,action)=>ipcRenderer.invoke('orbit:navigate-website',id,action),
  onOpenPage:(callback)=>{const handler=(_event,page)=>callback(page);ipcRenderer.on('orbit:open-page',handler);return ()=>ipcRenderer.removeListener('orbit:open-page',handler);},
  joinZoom:(url,mode)=>ipcRenderer.invoke('orbit:join-zoom',url,mode),
  showService:(id,bounds)=>ipcRenderer.invoke('orbit:show-service',id,bounds),
  reloadService:(id)=>ipcRenderer.invoke('orbit:reload-service',id),
  getConnection:()=>ipcRenderer.invoke('orbit:google-connection'),
  saveConnection:(input)=>ipcRenderer.invoke('orbit:google-config',input),
  connectGoogle:options=>ipcRenderer.invoke('orbit:google-connect',options),
  getLocalEvents:()=>ipcRenderer.invoke('orbit:local-events'),
  getApiStatus:()=>ipcRenderer.invoke('orbit:api-status'),
  saveApiSettings:input=>ipcRenderer.invoke('orbit:api-config',input),
  copyApiConfig:kind=>ipcRenderer.invoke('orbit:api-copy',kind),
  onEventsChanged:callback=>{const handler=(_event,events)=>callback(events);ipcRenderer.on('orbit:events-changed',handler);return ()=>ipcRenderer.removeListener('orbit:events-changed',handler);},
  onDataChanged:callback=>{const handler=()=>callback();ipcRenderer.on('orbit:data-changed',handler);return ()=>ipcRenderer.removeListener('orbit:data-changed',handler);},
  disconnectGoogle:()=>ipcRenderer.invoke('orbit:google-disconnect'),
  getMeetings:()=>ipcRenderer.invoke('orbit:google-meetings'),
  getSummary:()=>ipcRenderer.invoke('orbit:google-summary'),
  syncMeetings:(events)=>ipcRenderer.invoke('orbit:sync-meetings',events)
}));
